"""Update database

Revision ID: 007611a5f066
Revises: 10d9e4fd3b4c
Create Date: 2025-01-28 02:34:28.838553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007611a5f066'
down_revision = '10d9e4fd3b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblmedia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblmedia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=50), nullable=True),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
