"""update models

Revision ID: 03447b4d2928
Revises: 824ceb62475c
Create Date: 2025-01-01 13:49:40.528318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03447b4d2928'
down_revision = '824ceb62475c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblsteams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsteamgame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.Integer(), nullable=False),
    sa.Column('gameid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameid'], ['tblgames.id'], ),
    sa.ForeignKeyConstraint(['steamid'], ['tblsteams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsteamgame')
    op.drop_table('tblsteams')
    # ### end Alembic commands ###
