"""Password sütunu String olarak güncellendi

Revision ID: 08110a5c6717
Revises: d96eac62242d
Create Date: 2024-12-14 17:20:24.149060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08110a5c6717'
down_revision = 'd96eac62242d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
