"""update models

Revision ID: 08ed7e405d5a
Revises: 81667e9fe6ec
Create Date: 2025-01-05 14:45:40.194381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ed7e405d5a'
down_revision = '81667e9fe6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblmedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbltext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_message', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblmediaandtext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textid', sa.Integer(), nullable=False),
    sa.Column('mediaid', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['mediaid'], ['tblmedia.id'], ),
    sa.ForeignKeyConstraint(['textid'], ['tbltext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblmediaandtext')
    op.drop_table('tbltext')
    op.drop_table('tblmedia')
    # ### end Alembic commands ###
