"""Update database

Revision ID: 0ae95057a2d4
Revises: 48ff91a87f51
Create Date: 2025-01-28 11:59:40.895408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae95057a2d4'
down_revision = '48ff91a87f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbltext')
    op.drop_table('tblmedia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblmedia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=50), nullable=True),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbltext',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text_message', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
