"""Update database

Revision ID: 10d9e4fd3b4c
Revises: d691bde05ac0
Create Date: 2025-01-28 02:23:30.345933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d9e4fd3b4c'
down_revision = 'd691bde05ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblmedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=50), nullable=True),
    sa.Column('page_name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbltext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_message', sa.String(length=5000), nullable=True),
    sa.Column('page_name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbltext')
    op.drop_table('tblmedia')
    # ### end Alembic commands ###
