"""Initial migration

Revision ID: 11509ca9629c
Revises: cfaffadbbd85
Create Date: 2024-12-24 11:44:13.747706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11509ca9629c'
down_revision = 'cfaffadbbd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('logopath', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('adress', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsettings')
    # ### end Alembic commands ###
