"""Initial migration

Revision ID: 165a91648d4e
Revises: 7b14affe2b21
Create Date: 2024-12-19 11:15:52.990230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165a91648d4e'
down_revision = '7b14affe2b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblcomputerfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('videocard', sa.String(length=100), nullable=True),
    sa.Column('mothercard', sa.String(length=100), nullable=True),
    sa.Column('freez', sa.String(length=100), nullable=True),
    sa.Column('mouse', sa.String(length=100), nullable=True),
    sa.Column('headphone', sa.String(length=100), nullable=True),
    sa.Column('processor', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=100), nullable=True),
    sa.Column('screen', sa.String(length=100), nullable=True),
    sa.Column('keyboard', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblcomputerfiles')
    # ### end Alembic commands ###
