"""Initial migration

Revision ID: 2a1e8a2844a9
Revises: 165a91648d4e
Create Date: 2024-12-19 11:37:18.710349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1e8a2844a9'
down_revision = '165a91648d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblgames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iconpath', sa.String(length=50), nullable=True),
    sa.Column('photopath', sa.String(length=50), nullable=True),
    sa.Column('gamename', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsteams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iconpath', sa.String(length=50), nullable=True),
    sa.Column('gamename', sa.String(length=100), nullable=True),
    sa.Column('steamname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsteams')
    op.drop_table('tblgames')
    # ### end Alembic commands ###
