"""Initial migration

Revision ID: 5abf42e28f53
Revises: bde7b5f55dfd
Create Date: 2024-12-19 11:07:15.846402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abf42e28f53'
down_revision = 'bde7b5f55dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblfoods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblfoods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photopath', sa.VARCHAR(length=50), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
