"""Initial migration

Revision ID: 76080035d6c3
Revises: 0afa81cf81f1
Create Date: 2024-12-16 20:37:08.620616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76080035d6c3'
down_revision = '0afa81cf81f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False))
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
