"""Initial migration

Revision ID: 7b14affe2b21
Revises: 50b3de21f0a2
Create Date: 2024-12-19 11:15:26.646413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b14affe2b21'
down_revision = '50b3de21f0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblcomputerfiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblcomputerfiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('videocard', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mothercard', sa.VARCHAR(length=100), nullable=True),
    sa.Column('freez', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mouse', sa.VARCHAR(length=100), nullable=True),
    sa.Column('headphone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('processor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ram', sa.VARCHAR(length=100), nullable=True),
    sa.Column('screen', sa.VARCHAR(length=100), nullable=True),
    sa.Column('keyboard', sa.VARCHAR(length=100), nullable=True),
    sa.Column('path', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
