"""Initial migration

Revision ID: 800390177398
Revises: 915cb13a51f3
Create Date: 2024-12-16 11:39:07.790147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800390177398'
down_revision = '915cb13a51f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_tbl', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_tbl', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
