"""Initial migration

Revision ID: 81667e9fe6ec
Revises: 
Create Date: 2025-01-05 14:28:26.355830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81667e9fe6ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblarsive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagepath', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblcomputerfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('videocard', sa.String(length=100), nullable=True),
    sa.Column('mothercard', sa.String(length=100), nullable=True),
    sa.Column('freez', sa.String(length=100), nullable=True),
    sa.Column('mouse', sa.String(length=100), nullable=True),
    sa.Column('headphone', sa.String(length=100), nullable=True),
    sa.Column('processor', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=100), nullable=True),
    sa.Column('screen', sa.String(length=100), nullable=True),
    sa.Column('keyboard', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblfoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblgames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iconpath', sa.String(length=50), nullable=True),
    sa.Column('photopath', sa.String(length=50), nullable=True),
    sa.Column('gamename', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagepath', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('logopath', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('adress', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsteams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsteamgame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.Integer(), nullable=False),
    sa.Column('gameid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameid'], ['tblgames.id'], ),
    sa.ForeignKeyConstraint(['steamid'], ['tblsteams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsteamgame')
    op.drop_table('tblusers')
    op.drop_table('tblsteams')
    op.drop_table('tblsettings')
    op.drop_table('tblservice')
    op.drop_table('tblgames')
    op.drop_table('tblfoods')
    op.drop_table('tblcomputerfiles')
    op.drop_table('tblarsive')
    # ### end Alembic commands ###
