"""update models

Revision ID: 824ceb62475c
Revises: f34a2eb8681f
Create Date: 2025-01-01 13:49:00.737358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824ceb62475c'
down_revision = 'f34a2eb8681f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsteams')
    op.drop_table('tblsteamgame')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblsteamgame',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('steamid', sa.INTEGER(), nullable=False),
    sa.Column('gameid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gameid'], ['tblgames.id'], ),
    sa.ForeignKeyConstraint(['steamid'], ['tblsteams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsteams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gameid', sa.INTEGER(), nullable=False),
    sa.Column('steamname', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['tblgames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
