"""Initial migration

Revision ID: 82c18a7a3822
Revises: f34a2eb8681f
Create Date: 2025-01-01 13:46:24.733209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c18a7a3822'
down_revision = 'f34a2eb8681f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblsteamgame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.Integer(), nullable=False),
    sa.Column('gameid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameid'], ['tblgames.id'], ),
    sa.ForeignKeyConstraint(['steamid'], ['tblsteams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tblsteams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gameid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tblsteams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameid', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'tblgames', ['gameid'], ['id'])

    op.drop_table('tblsteamgame')
    # ### end Alembic commands ###
