"""Initial migration

Revision ID: 8ed06638a5e6
Revises: c2d28339f58b
Create Date: 2024-12-18 17:28:23.604085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed06638a5e6'
down_revision = 'c2d28339f58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbltext')
    op.drop_table('tblfoods')
    op.drop_table('tblmedia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblmedia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=50), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblfoods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('photopath', sa.VARCHAR(length=50), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbltext',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photoid', sa.INTEGER(), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('text', sa.VARCHAR(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['photoid'], ['tblmedia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
