"""Initial migration

Revision ID: 915cb13a51f3
Revises: 3444444dff77
Create Date: 2024-12-15 19:44:48.153587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915cb13a51f3'
down_revision = '3444444dff77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_tbl', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
