"""Initial migration

Revision ID: 96ad8822657c
Revises: 0f61061bf86b
Create Date: 2024-12-16 12:27:02.190674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ad8822657c'
down_revision = '0f61061bf86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['text_tbl.group_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_tbl')
    # ### end Alembic commands ###
