"""Initial migration

Revision ID: 98fed8e8a22c
Revises: 96ad8822657c
Create Date: 2024-12-16 12:31:28.701247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fed8e8a22c'
down_revision = '96ad8822657c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_tbl', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
