"""add column media_tbl

Revision ID: 9c6488f92155
Revises: c732de9256ef
Create Date: 2024-12-16 16:34:29.105761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6488f92155'
down_revision = 'c732de9256ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['text_tbl.group_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_tbl')
    # ### end Alembic commands ###
