"""Initial migration

Revision ID: af7c96500d26
Revises: edc75c2ad912
Create Date: 2024-12-18 22:33:38.720625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7c96500d26'
down_revision = 'edc75c2ad912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblfoods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblfoods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('photopath', sa.VARCHAR(length=50), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
