"""Initial migration

Revision ID: b74fdc68e135
Revises: bc5110e07c94
Create Date: 2024-12-28 14:16:51.560854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74fdc68e135'
down_revision = 'bc5110e07c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblgames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblgames',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('iconpath', sa.VARCHAR(length=50), nullable=True),
    sa.Column('photopath', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gamename', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text', sa.VARCHAR(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
