"""Initial migration

Revision ID: bc5110e07c94
Revises: ed5579f3f4f2
Create Date: 2024-12-28 14:14:03.735311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5110e07c94'
down_revision = 'ed5579f3f4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsteams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblsteams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('iconpath', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gamename', sa.VARCHAR(length=100), nullable=True),
    sa.Column('steamname', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
