"""Initial migration

Revision ID: cfaffadbbd85
Revises: 2a1e8a2844a9
Create Date: 2024-12-22 19:20:03.773410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfaffadbbd85'
down_revision = '2a1e8a2844a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagepath', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblservice')
    # ### end Alembic commands ###
