"""Initial migration

Revision ID: d691bde05ac0
Revises: 08ed7e405d5a
Create Date: 2025-01-28 02:10:12.880047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd691bde05ac0'
down_revision = '08ed7e405d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblmediaandtext')
    op.drop_table('tblmedia')
    op.drop_table('tbltext')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbltext',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text_message', sa.VARCHAR(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblmedia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblmediaandtext',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('textid', sa.INTEGER(), nullable=False),
    sa.Column('mediaid', sa.INTEGER(), nullable=False),
    sa.Column('page_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['mediaid'], ['tblmedia.id'], ),
    sa.ForeignKeyConstraint(['textid'], ['tbltext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
