"""Initial migration

Revision ID: ed5579f3f4f2
Revises: 11509ca9629c
Create Date: 2024-12-24 21:56:38.936503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5579f3f4f2'
down_revision = '11509ca9629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblarsive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagepath', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblarsive')
    # ### end Alembic commands ###
