"""Initial migration

Revision ID: f34a2eb8681f
Revises: b74fdc68e135
Create Date: 2024-12-28 14:17:40.161005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34a2eb8681f'
down_revision = 'b74fdc68e135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblgames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iconpath', sa.String(length=50), nullable=True),
    sa.Column('photopath', sa.String(length=50), nullable=True),
    sa.Column('gamename', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblsteams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameid', sa.Integer(), nullable=False),
    sa.Column('steamname', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['tblgames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblsteams')
    op.drop_table('tblgames')
    # ### end Alembic commands ###
