"""Initial migration

Revision ID: f4622e87e24a
Revises: 8ed06638a5e6
Create Date: 2024-12-18 17:28:39.237891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4622e87e24a'
down_revision = '8ed06638a5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbltext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblmedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['tbltext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblmedia')
    op.drop_table('tbltext')
    # ### end Alembic commands ###
